### ISSUE TITLE
Proposal: Vestfold Dev Community Event 24.November

### ISSUE THREAD

**Issue by pavsaund** [pavsaund/VestfoldDevelopers#2]
## Background 
Ole-Edvard from Vestfold Whitehats is arranging a meetup this date and has proposed to expand it since the topic is quite interesting for all developers. A community event is great for mingling, creating contacts and expanding horizons. These types of Community Days are something we may do once to twice a year.

## Proposal
This is a proposal to arrange a mini-community event on the 24th of November. 
Would like to arrange an evening with 3-4 talks of 30 minutes each with a 5 or 10 minute break between. Each development community in Vestfold can have a slot they can fill + a wildcard.

## Location 
Høyskolen i Vestfold

### 10 minute breaks
- [17:25-17:30] Intro
- [17:30-18:00] Session 1 - Vestfold Whitehats
- [18:10-18:40] Session 2 - NNUG 
- [18:40-19:10] Break w/ refreshments
- [19:10-19:40] Session 3 - JavaBin
- [19:50-20:20] Session 4 - Open / WildCard / CFP
- [20:20-20:25] Closing

### 5 minute breaks
- [17:25-17:30] Intro
- [17:30-18:00] Session 1 - Vestfold Whitehats
- [18:05-18:35] Session 2 - NNUG 
- [18:35-19:15] Break w/ refreshments
- [19:15-19:45] Session 3 - JavaBin
- [19:50-20:20] Session 4 - Open / WildCard / CFP
- [20:20-20:25] Closing

### Sponsorship
We need to gauge how many we expect to show up and gather sponsor-funds based on that. Perhaps each group can play a part in bringing in funds through direct sponsorship or from companies. Perhaps each talk can be "sponsored" by a company, so they may be promoted.

### Atendee fee
~~Should we consider charging a symbolic fee from each member? I would propose we avoid this if we can.~~
Based on feedback from Høyskolen i Vestfold, and the spirit of our community, we should go for an event which is free to attend.

## Sign-up
Either create a separate signup for each group with binding registration, or create a new meetup group, which we link to from the others.

### Equipment
Speakers can bring their own devices. Should verify cable / sound possibilities.
Have a universal "clicker" that speakers can use
### Recording
Would be great to have the possibility to record the event. 
### Pictures
Documenting the event through pictures would be a great idea. Perhaps someone from the community can help out here? 

- Attendees
- Speakers
- Sponsors
- Final group photo

Let's discuss.

**Comment by pavsaund** [comment]
The most important matter to decide in this issue is a commitment from alle the meetup groups involved. We can branch off and create separate issues for each sub-category so we can have clean discussions on those topics.

To be perfectly clear: We have a date, we have a location. What we need is commitment from the dev communities.

- [x] Vestfold Whitehats
- [x] NNUG Vestfold
- [ ] JavaBin Vestfold

**Comment by anemaecore** [comment]
I vote that we do not require any fees from participants.

As a matter of fact I just spoke with Thomas at "Høgskolen i Vestfold", and he mentioned that they have a cafeteria nearby that normally closes at 16:00, but that he may be able to persuade to keep open for our event, depending on how many that shows up for this event. In any case, the cafeteria is where we should eat.

Should I approach the various Vestfold company department heads and encourage them to come to this event? 

I could create an advertisment email, informing the community of the event.

**Comment by pavsaund** [comment]
Just received feedback that JavaBin are game! :)

**Comment by pavsaund** [comment]
Closing this issue since we have a commitment from all involved groups. Follow up with other issues as part of project: https://github.com/pavsaund/VestfoldDevelopers/projects/1
